# Define the schema names and method names for the SOAP client.
# These mappings are used to determine the appropriate WSDL and method to call based on the type of entity.
SCHEMA_NAME = {
    "User": "User/User.wsdl",
    "Organization": "Organization/Organization.wsdl",
    "ServiceProvider": "ServiceProvider/ServiceProvider.wsdl",
    "Extension": "Extension/Extension.wsdl",
    "Billing": "Billing/Billing.wsdl",
    "Report": "Report/Report.wsdl",
    "Channel": "Channel/Channel.wsdl",
    "PBX": "PBX/PBX.wsdl",
}
METHOD_NAME = {
    "User": {
        "Add": "AddUser",
        "Get": "GetUsers",
        "Edit": "EditUser",
        "Delete": "DelUser",
        "GetDetails": "GetUserDetails",
        "GetGroups": "GetUserGroups",
        "SetCP": "SetUserCpAccess",
        "SetStatus": "SetUserStatus",
        "SetPL": "SetUserPL",
        "GetPL": "GetUserPL",
        "UpdatePL": "UpdateUserPL",
    },
    "Organization": {
        "Add": "AddOrganization",
        "Get": "GetOrganizations",
        "Edit": "EditOrganization",
        "Delete": "DelOrganization",
        "GetDetails": "GetOrganizationDetails",
        "Move": "MoveOrganizations",
        "SetCP": "SetOrganizationCpAccess",
        "SetStatus": "SetOrganizationStatus",
        "SetPL": "SetOrganizationPL",
        "GetPL": "GetOrganizationPL",
        "UpdatePL": "UpdateOrganizationPL",
    },
    "ServiceProvider": {
        "Add": "AddServiceProvider",
        "Get": "GetServiceProviders",
        "Edit": "EditServiceProvider",
        "Delete": "DelServiceProvider",
        "GetDetails": "GetServiceProviderDetails",
        "SetCP": "SetServiceProviderCpAccess",
        "SetStatus": "SetServiceProviderStatus",
        "SetPL": "SetServiceProviderPL",
        "GetPL": "GetServiceProviderPL",
        "UpdatePL": "UpdateServiceProviderPL",
    },
    "Extension": {
        "AddExtension": "AddExtension",
        "GetExtensions": "GetExtensions",
        "DeleteExtension": "DelExtension",
        "GetProvisionFile": "GetProvisionFile",
        "GetQueueAgents": "GetQueueAgents",
        "GetQueueMembership": "GetQueueMembership",
        "GetScheduledConferences": "GetScheduledConferences",
        "GetScheduledConferenceDetails": "GetScheduledConferenceDetails",
        "GetAuthCallerID": "GetAuthCallerID",
        "GetAuthCallerIDRecharges": "GetAuthCallerIDRecharges",
        "GetAvailableCallerID": "GetAvailableCallerID",
        "GetCallRecordingSettings": "GetCallRecordingSettings",
        "GetCallRulesIn": "GetCallRulesIn",
        "GetCardCode": "GetCardCode",
        "GetCardCodeRecharges": "GetCardCodeRecharges",
        "GetConferenceSettings": "GetConferenceSettings",
        "GetExtensionDetails": "GetExtensionDetails",
        "GetExtensionSettings": "GetExtensionSettings",
        "GetFaxCenterSettings": "GetFaxCenterSettings",
        "GetScheduledConferenceSessions": "GetScheduledConferenceSessions",
        "GetSIPPreferences": "GetSIPPreferences",
        "GetVoicemailSettings": "GetVoicemailSettings",
    },
    "Billing": {
        "GetChargingPlans": "GetChargingPlans",
        "GetChargingPackages": "GetChargingPackages",
        "GetChargingPlanDetails": "GetChargingPlanDetails",
        "GetDestinationExceptions": "GetDestinationExceptions",
        "GetRecharges": "GetRecharges",
    },
    "Report": {
        "CallCosts": "CallCosts",
        "CallReport": "CallReport",
        "QuickStats": "QuickStats",
    },
    "Channel": {
        "GetChannels": "GetChannels",
        "GetCodecs": "GetCodecs",
        "GetPublicNo": "GetPublicNo",
        "GetPublicNoPoll": "GetPublicNoPoll",
        "GetCallRulesOut": "GetCallRulesOut",
        "GetCallRulesOutGroup": "GetCallRulesOutGroup",
        "GetChannelGroupPoll": "GetChannelGroupPoll",
        "GetChannelGroups": "GetChannelGroups",
    },
    "PBX": {
        "GetCustomAlerts": "GetCustomAlerts",
        "GetCustomButtons": "GetCustomButtons",
        "GetDeviceDetails": "GetDeviceDetails",
        "GetDevices": "GetDevices", 
        "GetEquipmentList": "GetEquipmentList",
        "GetFileLanguages": "GetFileLanguages",
        "GetFolders": "GetFolders",
        "GetInterfaceLang": "GetInterfaceLang",
        "GetOwnedSounds": "GetOwnedSounds",
        "GetPhoneLang": "GetPhoneLang",
        "GetRegions": "GetRegions",
        "GetSchemaVersions": "GetSchemaVersions",
        "GetSharedSounds": "GetSharedSounds",
        "GetTemplates": "GetTemplates",
        "GetTimeIntervalBlocks": "GetTimeIntervalBlocks",
        "GetTimeIntervals": "GetTimeIntervals",
        "GetTimezone": "GetTimezone",
    },
}
